# Generated by Django 5.2.5 on 2025-09-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='exp',
            new_name='xp',
        ),
    ]
