# Generated by Django 5.2.5 on 2025-09-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_habits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_leagues',
            field=models.IntegerField(default=0),
        ),
    ]
